### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by giampaolo** [btimby/reloadconf#13]
Not sure if it's related to #12 but I've just bumped into this:

```
[reloadconf DEBUG] Backing up /etc/postfix/master.cf to /etc/postfix/master.cf.prev
[reloadconf ERROR] Failure, restoring config
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/reloadconf/__init__.py", line 430, in test_and_swap
    self.install_config(config)
  File "/usr/local/lib/python3.5/dist-packages/reloadconf/__init__.py", line 404, in install_config
    dst = [p for p in self.config if basename(p) == fn][0]
IndexError: list index out of range
```

Cmdline I've used:

```
reloadconf \
    --debug \
    --wait-for-path="/var/log/mail.log" \
    --wait-for-sock="localhost:25" \
    --config="/etc/postfix/master.cf" \
    --config="/etc/postfix/main.cf" \
    --watch="/conf/" \
    --test="postfix check" \
    --command="tail -F /var/log/mail.log" \
    --reload="postfix reload" 
```

**Comment by giampaolo** [comment]
This happens when I remove a config file being watched (e.g. `rm conf/master.cf`).
It doesn't if I use `--inotify` though.
